### ISSUE TITLE
Q: How do I flash the device?

### ISSUE THREAD

**Issue by axelriet** [akpc806a/CAN_Logger#4]
Supposing I build the firmware, how do I flash it to the device? What do you recommend as SWD hardware that would work with ChibiStudio on a PC running Windows and allow flashing/debugging?

**Comment by akpc806a** [comment]
Hello,
i usually use this type of dongles 
https://www.amazon.com/HiLetgo-Emulator-Downloader-Programmer-STM32F103C8T6/dp/B07SQV6VLZ
which are clones of ST-Link V2.
You need to adjust setting in your IDE for SWD mode (not JTAG) and software reset.

The compiled binary file is here: https://sites.google.com/site/akpc806a/ch__wrap_files__delay_startup.hex
You can use ST-Link Utility for Windows or STM32CubeProg for Linux to flash this binary

**Comment by axelriet** [comment]
Thanks!
